/** Arabic labels copied from the Flutter app translations (lib/core/translations). */
export const APP_LABELS: Record<string, string> = {
  "common_all": "الكل",
  "fav_cat_bouquets": "باقات الورد",
  "fav_cat_cake": "الكيك",
  "fav_cat_cherry": "الكرز",
  "fav_cat_chocolate": "الشوكولاه",
  "fav_cat_lavender": "اللافندر",
  "filter_budget": "حدود ميزانيتك",
  "filter_delivery": "التوصيل",
  "filter_filters": "الفلاتر",
  "filter_gift_type": "نوع الهدية",
  "filter_occasion": "نوع المناسبة",
  "filter_person": "الشخص",
  "filter_price": "السعر",
  "filter_show_results": "أظهار النتائج ( @count )",
  "filter_sort_by": "ترتيب حسب",
  "filter_title": "الترتيب و الفلترة",
  "gov_anbar": "الأنبار",
  "gov_babylon": "بابل",
  "gov_baghdad": "بغداد",
  "gov_basra": "البصرة",
  "gov_dhi_qar": "ذي قار",
  "gov_diyala": "ديالى",
  "gov_duhok": "دهوك",
  "gov_erbil": "أربيل",
  "gov_karbala": "كربلاء",
  "gov_kirkuk": "كركوك",
  "gov_maysan": "ميسان",
  "gov_muthanna": "المثنى",
  "gov_najaf": "النجف",
  "gov_nineveh": "نينوى",
  "gov_qadisiyyah": "القادسية",
  "gov_saladin": "صلاح الدين",
  "gov_sulaymaniyah": "السليمانية",
  "gov_wasit": "واسط",
  "opt_anniversary": "ذكرى",
  "opt_apology": "اعتذار",
  "opt_birthday": "عيد ميلاد",
  "opt_brother": "أخ",
  "opt_budget_high": "50 – 100 ألف",
  "opt_budget_low": "أقل من 25 ألف",
  "opt_budget_mid": "25 – 50 ألف",
  "opt_budget_vip": "أكثر من 100 ألف",
  "opt_cake": "كيك",
  "opt_chocolate": "شوكولاه",
  "opt_colleague": "زميل",
  "opt_congrats": "تهنئة",
  "opt_dad": "أب",
  "opt_delivery_today": "تصل اليوم",
  "opt_delivery_tomorrow": "تصل غدًا",
  "opt_flowers": "ورود",
  "opt_friend": "صديق",
  "opt_graduation": "تخرج",
  "opt_kids": "أطفال",
  "opt_mom": "أم",
  "opt_newborn": "مولود جديد",
  "opt_partner": "شريك",
  "opt_perfume": "عطور",
  "opt_pickup": "استلام",
  "opt_plants": "نباتات",
  "opt_sister": "أخت",
  "opt_thanks": "شكر",
  "opt_toys": "ألعاب",
  "opt_wedding": "زفاف",
  "product_badge_fast": "توصيل سريع",
  "product_badge_free_delivery": "طلبك مؤهل للتوصيل المجاني",
  "product_badge_mastercard": "يتوفر دفع بماستر كارد",
  "product_badge_natural": "نبات طبيعي",
  "sg_opt_boxes": "بوكسات",
  "sg_opt_candles": "شموع",
  "sg_opt_care": "عناية",
  "sg_opt_custom": "مخصص",
  "sg_opt_fathers": "عيد الأب",
  "sg_opt_flower_bouquets": "باقات ورد",
  "sg_opt_formal": "مناسبة رسمية",
  "sg_opt_friends": "أصدقاء",
  "sg_opt_gifts_men": "هدايا للرجال",
  "sg_opt_gifts_women": "هدايا للنساء",
  "sg_opt_grad_success": "تخرج / نجاح",
  "sg_opt_grandparents": "أجداد",
  "sg_opt_home": "منزل",
  "sg_opt_jewelry": "مجوهرات",
  "sg_opt_mothers": "عيد الأم",
  "sg_opt_no_occasion": "بدون مناسبة",
  "sg_opt_other": "أخرى",
  "sg_opt_other_person": "شخص آخر",
  "sg_opt_parents": "أم / أب",
  "sg_opt_sibling": "أخ / أخت",
  "sg_opt_spouse": "زوج / زوجة",
  "sg_opt_sweets": "حلويات",
  "sg_opt_valentines": "عيد الحب",
  "sg_opt_wedding_engagement": "زواج / خطوبة",
  "sg_opt_work": "عمل",
  "sg_opt_work_congrats": "تهنئة عمل",
  "sort_newest": "الأحدث",
  "sort_popular": "الأكثر شهرة",
  "sort_price_asc": "السعر: من الأقل للأعلى",
  "sort_price_desc": "السعر: من الأعلى للأقل",
  "support_subject_delivery": "توصيل",
  "support_subject_order": "طلب",
  "support_subject_other": "أخرى",
  "support_subject_payment": "دفع"
};

export function appLabel(key: string | null | undefined): string {
  if (!key) return "—";
  return APP_LABELS[key] ?? key;
}
